name: TSC-check-script
on:
    push:
        branches: [typescript]
    pull_request:
        branches: [typescript]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: script
    run: tscTest.sh
    shell: bash
